###get users
###get all users
GET http://localhost:3000/users

###get a user by id

GET http://localhost:3000/users/4

###create a user
POST  http://localhost:3000/users
Content-Type: application/json

{
    "name":"juan",
    "email":"juan@gmail.com",
    "password":"123456789"
}
### update a user
PUT   http://localhost:3000/users/6
Content-Type: application/json

{
    "name":"pepaPig",
    "email":"juan@gmail.com",
    "password":"123456789"
}
### delete a user
DELETE  http://localhost:3000/users/6

